"""added recipe type

Revision ID: 24d0eff5651c
Revises: d58834d82513
Create Date: 2018-07-26 19:18:25.794960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d0eff5651c'
down_revision = 'd58834d82513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokes', sa.Column('recipe_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokes', 'recipe_type')
    # ### end Alembic commands ###
