"""Poke table with unique name and bool for if recipes work

Revision ID: d58834d82513
Revises: 
Create Date: 2018-07-25 10:37:12.855371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58834d82513'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('best_recipe', sa.String(length=100), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('attracted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokes_best_recipe'), 'pokes', ['best_recipe'], unique=False)
    op.create_index(op.f('ix_pokes_name'), 'pokes', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokes_name'), table_name='pokes')
    op.drop_index(op.f('ix_pokes_best_recipe'), table_name='pokes')
    op.drop_table('pokes')
    # ### end Alembic commands ###
